-- properties テーブル作成SQL
-- Generated from HubSpot API properties

CREATE TABLE properties (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hubspot_id VARCHAR(255) UNIQUE NOT NULL,
    bukken_name TEXT NULL COMMENT '物件名',
    bukken_state TEXT NULL COMMENT '都道府県',
    bukken_city TEXT NULL COMMENT '市区町村',
    bukken_address TEXT NULL COMMENT '番地以下',
    land_number TEXT NULL COMMENT '地番',
    bukken_type TEXT NULL COMMENT '種別',
    bukken_structure TEXT NULL COMMENT '構造',
    bukken_property_land TEXT NULL COMMENT '建物/土地の種類',
    bukken_floor DECIMAL(20, 2) NULL COMMENT '階数',
    bukken_houses DECIMAL(20, 2) NULL COMMENT '戸数',
    bukken_completion_years DATETIME NULL COMMENT '竣工年月',
    bukken_age DECIMAL(20, 2) NULL COMMENT '築年数',
    total_floor_area DECIMAL(20, 2) NULL COMMENT '延床面積',
    bukken_building_cost_estimate DECIMAL(20, 2) NULL COMMENT '建物積算',
    bukken_land_area DECIMAL(20, 2) NULL COMMENT '土地面積',
    access_road TEXT NULL COMMENT '接道',
    tsubo DECIMAL(20, 2) NULL COMMENT '坪',
    bukken_road_price DECIMAL(20, 2) NULL COMMENT '路線価',
    bukken_land_estimation DECIMAL(20, 2) NULL COMMENT '土地積算',
    electricity TEXT NULL COMMENT '電気',
    gas TEXT NULL COMMENT 'ガス',
    water_supply TEXT NULL COMMENT '水道',
    sewage TEXT NULL COMMENT '下水',
    parking TEXT NULL COMMENT '駐車場',
    urban_planning TEXT NULL COMMENT '都市計画',
    fire_prevention_area TEXT NULL COMMENT '防火地域',
    zoning TEXT NULL COMMENT '用途地域',
    altitude_area TEXT NULL COMMENT '高度地区',
    building_coverage_ratio DECIMAL(20, 2) NULL COMMENT '建蔽率',
    floor_area_ratio DECIMAL(20, 2) NULL COMMENT '容積率',
    zoning2 TEXT NULL COMMENT '用途地域2',
    building_coverage_ratio2 DECIMAL(20, 2) NULL COMMENT '建蔽率2',
    floor_area_ratio2 DECIMAL(20, 2) NULL COMMENT '容積率2',
    other_restrictions TEXT NULL COMMENT 'その他制限',
    property_remarks TEXT NULL COMMENT '備考（物件情報）',
    bukken_creator TEXT NULL COMMENT '作成者',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_synced_at TIMESTAMP NULL,
    INDEX idx_hubspot_id (hubspot_id),
    INDEX idx_last_synced_at (last_synced_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='properties';