-- contacts テーブル作成SQL
-- Generated from HubSpot API properties

CREATE TABLE contacts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hubspot_id VARCHAR(255) UNIQUE NOT NULL,
    lastname TEXT NULL COMMENT 'Last Name',
    firstname TEXT NULL COMMENT 'First Name',
    email TEXT NOT NULL COMMENT 'Email',
    phone TEXT NULL COMMENT 'Phone Number',
    phone2 TEXT NULL COMMENT '電話番号2',
    contact_state JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 東京都, 1: 神奈川県, 2: 千葉県, 3: 埼玉県, 4: 北海道, 5: 青森県, 6: 岩手県, 7: 宮城県, 8: 秋田県, 9: 山形県, 10: 福島県, 11: 茨城県, 12: 栃木県, 13: 群馬県, 14: 新潟県, 15: 富山県, 16: 石川県, 17: 福井県, 18: 山梨県, 19: 長野県, 20: 岐阜県, 21: 静岡県, 22: 愛知県, 23: 三重県, 24: 滋賀県, 25: 京都府, 26: 大阪府, 27: 兵庫県, 28: 奈良県, 29: 和歌山県, 30: 鳥取県, 31: 島根県, 32: 岡山県, 33: 広島県, 34: 山口県, 35: 徳島県, 36: 香川県, 37: 愛媛県, 38: 高知県, 39: 福岡県, 40: 佐賀県, 41: 長崎県, 42: 熊本県, 43: 大分県, 44: 宮崎県, 45: 鹿児島県, 46: 沖縄県',
    contact_city TEXT NULL COMMENT '市区町村',
    became_a_partner_date DATETIME NULL COMMENT 'パートナーになった日付',
    contractor_memo TEXT NULL COMMENT 'メモ',
    contractor_channel JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: RAINS, 1: 健美家, 2: 楽待, 3: ハトマーク, 4: ラビーネット, 5: eight, 6: 業者会, 7: BIZMAP, 8: リファラル, 9: HP',
    contractor_last_url_click DATETIME NULL COMMENT 'EメールURLクリック最終日時',
    hubspot_owner_id BIGINT NULL COMMENT 'Contact owner (owners.id)',
    hubspot_old_owner_id BIGINT NULL COMMENT 'コンタクト担当（前任者） (owners.id)',
    contact_sales_outbound BIGINT NULL COMMENT '初回取得者 (owners.id)',
    contractor_follow_rank JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: S, 1: A, 2: B, 3: C, 4: D',
    contractor_buy_phase JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: S, 1: A, 2: B, 3: C, 4: D, 5: Z',
    contractor_buy_phase_date DATETIME NULL COMMENT '仕入フェーズ更新日',
    contractor_sell_phase JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: S, 1: A, 2: B, 3: C, 4: D, 5: Z',
    contractor_sell_phase_date DATETIME NULL COMMENT '販売フェーズ更新日',
    contractor_industry JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 売買仲介（エンド）, 1: 売買仲介（業者）, 2: 買取, 3: 買取（保有）, 4: 賃貸仲介, 5: 賃貸管理, 6: その他',
    contractor_property_type JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 1棟AP, 1: 1棟MS, 2: 区分（投資）, 3: ビル, 4: 土地, 5: 戸建て, 6: その他',
    contractor_buy_or_sell JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 仕入, 1: 売却',
    contractor_ap JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    contractor_type JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 大手仲介, 1: 元・大手仲介',
    affiliation JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 大手仲介, 1: 物上げ, 2: 銀行（系仲介）, 3: 宅建番号5番以上, 4: 大手アパート開発会社（系仲介）, 5: その他',
    graduate_experience JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 大手仲介, 1: 銀行（系仲介）, 2: 証券会社（系仲介）, 3: 中古アパート買取, 4: 保険会社',
    contractor_broker JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    information_acquisition_route JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: オーナー管理, 1: 士業（弁護士・税理士）, 2: 物上げ, 3: 相続, 4: 任売, 5: その他',
    property_information_share JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: OK, 1: NG',
    contractor_area JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 東京, 1: 神奈川, 2: 千葉, 3: 埼玉, 4: その他（関東）, 5: その他（北海道）, 6: その他（東北）, 7: その他（中部）, 8: その他（関西）, 9: その他（九州）, 10: その他（四国）, 11: その他（沖縄）, 12: 全国, 13: その他（海外）',
    contractor_area_category JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 狭域の郊外（地元特化）, 1: 1都3県（郊外寄り）, 2: 1都3県（23区寄り）, 3: 23区, 4: 都心5区',
    contractor_gross2 JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 〜1億, 1: 1〜3億, 2: 3〜5億, 3: 5〜10億, 4: 10億以上, 5: その他',
    assessment_community JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: なし, 1: 1〜3社, 2: 4〜9社, 3: 10〜19社, 4: 20社〜',
    assessment_community_detail TEXT NULL COMMENT 'APの紹介(査定)コミュニティ（詳細）',
    increase_referrals JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    ap_number JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 年6件以上, 1: 年3〜5件, 2: 年2件, 3: 年1件, 4: 数年に1件, 5: 取り扱い無し',
    ap_achievement JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 年6件以上, 1: 年3〜5件, 2: 年2件, 3: 年1件, 4: 数件に1件, 5: 実績なし',
    information_matchmaking JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 全部見合っている, 1: ほとんど見合っている, 2: 半分程度見合っている, 3: ほとんど見合っていない, 4: 全く見合ってない',
    personal_sales JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    santame JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: OK, 1: NG',
    ap_conditions JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: OK, 1: NG',
    decision_flow JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 稟議なし（社長直下）, 1: 稟議あり, 2: その他',
    contact_service_area JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 東京, 1: 神奈川, 2: 千葉, 3: 埼玉, 4: その他（関東）, 5: その他（北海道）, 6: その他（東北）, 7: その他（中部）, 8: その他（関西）, 9: その他（九州）, 10: その他（四国）, 11: その他（沖縄）, 12: 全国, 13: その他（海外）',
    contact_area_details TEXT NULL COMMENT 'エリア詳細',
    contact_sales_gross JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: -3,000, 1: 3,000-5,000, 2: 5,000-10,000, 3: 1〜3億, 4: 3〜5億, 5: 5億〜10億, 6: 10億以上, 7: その他',
    contact_own_funds JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 0 -500, 1: -1000, 2: -2000, 3: 2000-',
    contractor_yield TEXT NULL COMMENT '利回り',
    contact_yield JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 7%-, 1: 8%-, 2: 9%-, 3: 10%-',
    contractor_bank JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 静岡銀行, 1: トラスト, 2: 滋賀銀行, 3: auじぶん銀行, 4: オリックス銀行, 5: あすか信組, 6: SBJ銀行, 7: 香川銀行, 8: 関西みらい, 9: 西京銀行, 10: 湘南信用金庫, 11: スルガ銀行, 12: セゾンファンデックス, 13: 千葉銀行, 14: 東京シティ信用金庫, 15: 東京ベイ信用金庫, 16: 東和銀行, 17: 徳島大正銀行, 18: 東日本銀行, 19: 山梨中央銀行, 20: 横浜銀行',
    contact_station_distance JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 10分以内, 1: 15分以内, 2: 20分以内, 3: バス便',
    contact_building_age JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 1年未満（新築）, 1: 〜10年以内, 2: 10〜20年以内, 3: 20年〜25年以内, 4: 25年〜, 5: 旧耐震 （1950年から1981年5月31日）',
    contact_building_structure JSON NULL COMMENT 'JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 木造, 1: 軽量鉄骨造, 2: S造, 3: RC造, 4: SRC造',
    contact_supplement TEXT NULL COMMENT '補足',
    associatedcompanyid DECIMAL(20, 2) NULL COMMENT 'Primary Associated Company ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_synced_at TIMESTAMP NULL,
    INDEX idx_hubspot_id (hubspot_id),
    INDEX idx_last_synced_at (last_synced_at),
    INDEX idx_hubspot_owner_id (hubspot_owner_id),
    INDEX idx_hubspot_old_owner_id (hubspot_old_owner_id),
    INDEX idx_contact_sales_outbound (contact_sales_outbound),
    FOREIGN KEY (hubspot_owner_id) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (hubspot_old_owner_id) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (contact_sales_outbound) REFERENCES owners(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='contacts';