-- deals_purchase テーブル作成SQL（仕入取引）
-- Generated from HubSpot API properties
-- パイプラインID: 675713658

CREATE TABLE deals_purchase (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hubspot_id VARCHAR(255) UNIQUE NOT NULL,
    dealname TEXT NULL COMMENT 'Deal Name',
    bukken_created DATETIME NULL COMMENT '情報取得日',
    hubspot_owner_id BIGINT NULL COMMENT 'Deal owner (owners.id)',
    lead_acquirer BIGINT NULL COMMENT 'リード取得者 (owners.id)',
    deal_creator BIGINT NULL COMMENT '作成者 (owners.id)',
    deal_non_applicable JSON NULL COMMENT '非該当物件。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    buy_commercial_flow TEXT NULL COMMENT '商流',
    sales_price DECIMAL(20, 2) NULL COMMENT '紹介価格',
    answer_price DECIMAL(20, 2) NULL COMMENT '返答価格',
    bukken_survey_date DATETIME NULL COMMENT '現地調査日',
    research_purchase_price_date DATETIME NULL COMMENT '買付提出日',
    research_purchase_price DECIMAL(20, 2) NULL COMMENT '仕入価格',
    contract_date DATETIME NULL COMMENT '契約日',
    settlement_date DATETIME NULL COMMENT '決済日',
    dealstage BIGINT NULL COMMENT 'Deal Stage (pipeline_stages.id)',
    memo TEXT NULL COMMENT 'メモ',
    acquisition_channel JSON NULL COMMENT '獲得チャネル。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 自己客, 1: アウトバウンド',
    company_name TEXT NULL COMMENT '（一時利用）仲介会社名',
    deal_hold_date DATETIME NULL COMMENT '保留日',
    deal_survey_review_date DATETIME NULL COMMENT '調査検討日',
    deal_probability_a_date DATETIME NULL COMMENT '見込み確度A設定日',
    deal_probability_b_date DATETIME NULL COMMENT '見込み確度B設定日',
    deal_farewell_date DATETIME NULL COMMENT '見送り日',
    deal_lost_date DATETIME NULL COMMENT '失注日',
    sales_yield DECIMAL(20, 2) NULL COMMENT '利回り',
    road_price DECIMAL(20, 2) NULL COMMENT '路線価',
    sales_price_land DECIMAL(20, 2) NULL COMMENT '土地積算',
    sales_price_structure DECIMAL(20, 2) NULL COMMENT '建物積算',
    bukken_addition DECIMAL(20, 2) NULL COMMENT '積算',
    bukken_addition_rate DECIMAL(20, 2) NULL COMMENT '積算率',
    current_situation DECIMAL(20, 2) NULL COMMENT '現況',
    current_yield DECIMAL(20, 2) NULL COMMENT '現況利回り',
    full_occupancy DECIMAL(20, 2) NULL COMMENT '満室',
    full_occupancy_yield DECIMAL(20, 2) NULL COMMENT '満室利回り',
    research_desired_selling_price DECIMAL(20, 2) NULL COMMENT '【希望】想定売却価格',
    research_desired_yield DECIMAL(20, 2) NULL COMMENT '【希望】利回り',
    research_desired_gross_profit DECIMAL(20, 2) NULL COMMENT '【希望】粗利',
    research_lower_selling_price DECIMAL(20, 2) NULL COMMENT '【下限】想定売却価格',
    research_lower_yield DECIMAL(20, 2) NULL COMMENT '【下限】利回り',
    research_lower_gross_profit DECIMAL(20, 2) NULL COMMENT '【下限】粗利',
    exit_strategy JSON NULL COMMENT '出口戦略。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: CF, 1: 減価償却',
    possession JSON NULL COMMENT '中長期保有の可能性。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    research_ng_reason JSON NULL COMMENT 'NG理由。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 金額負け(他決), 1: 売主都合の売止, 2: 遵法性違反(瑕疵含む), 3: 銀行評価NG, 4: 売主金額合意NG',
    research_ng_reason_detail TEXT NULL COMMENT 'NG理由（詳細）',
    follow_up JSON NULL COMMENT '追客余地。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: はい, 1: いいえ',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_synced_at TIMESTAMP NULL,
    INDEX idx_hubspot_id (hubspot_id),
    INDEX idx_last_synced_at (last_synced_at),
    INDEX idx_hubspot_owner_id (hubspot_owner_id),
    INDEX idx_lead_acquirer (lead_acquirer),
    INDEX idx_deal_creator (deal_creator),
    INDEX idx_dealstage (dealstage),
    FOREIGN KEY (hubspot_owner_id) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (lead_acquirer) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (deal_creator) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (dealstage) REFERENCES pipeline_stages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仕入取引テーブル';