-- deals_sales テーブル作成SQL（販売取引）
-- Generated from HubSpot API properties
-- パイプラインID: 682910274

CREATE TABLE deals_sales (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hubspot_id VARCHAR(255) UNIQUE NOT NULL,
    dealname TEXT NULL COMMENT 'Deal Name',
    dealstage BIGINT NULL COMMENT 'Deal Stage (pipeline_stages.id)',
    bukken_created DATETIME NULL COMMENT '情報取得日',
    introduction_datetime DATETIME NULL COMMENT '紹介日時',
    hubspot_owner_id BIGINT NULL COMMENT 'Deal owner (owners.id)',
    lead_acquirer BIGINT NULL COMMENT 'リード取得者 (owners.id)',
    deal_creator BIGINT NULL COMMENT '作成者 (owners.id)',
    buy_commercial_flow TEXT NULL COMMENT '商流',
    sales_price DECIMAL(20, 2) NULL COMMENT '紹介価格',
    sales_answer_price DECIMAL(20, 2) NULL COMMENT '回答価格',
    purchase_conditions JSON NULL COMMENT '買取条件。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 現況, 1: 空渡し, 2: 更地渡し, 3: その他',
    buyer TEXT NULL COMMENT '買主',
    purchase_date DATETIME NULL COMMENT '買付取得日',
    sales_sales_price DECIMAL(20, 2) NULL COMMENT '販売価格',
    contract_date DATETIME NULL COMMENT '契約日',
    settlement_date DATETIME NULL COMMENT '決済日',
    memo TEXT NULL COMMENT 'メモ',
    final_closing_price DECIMAL(20, 2) NULL COMMENT '【最終】販売価格',
    final_closing_profit DECIMAL(20, 2) NULL COMMENT '【最終】粗利',
    research_desired_selling_price DECIMAL(20, 2) NULL COMMENT '【希望】想定売却価格',
    research_desired_yield DECIMAL(20, 2) NULL COMMENT '【希望】利回り',
    research_desired_gross_profit DECIMAL(20, 2) NULL COMMENT '【希望】粗利',
    research_lower_selling_price DECIMAL(20, 2) NULL COMMENT '【下限】想定売却価格',
    research_lower_yield DECIMAL(20, 2) NULL COMMENT '【下限】利回り',
    research_lower_gross_profit DECIMAL(20, 2) NULL COMMENT '【下限】粗利',
    deal_disclosure_date DATETIME NULL COMMENT '資料開示日',
    deal_survey_review_date DATETIME NULL COMMENT '調査検討日',
    deal_probability_b_date DATETIME NULL COMMENT '見込み確度B設定日',
    deal_probability_a_date DATETIME NULL COMMENT '見込み確度A設定日',
    deal_farewell_date DATETIME NULL COMMENT '見送り日',
    deal_lost_date DATETIME NULL COMMENT '失注日',
    sales_ng_reason JSON NULL COMMENT 'NG理由（販売）。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 他決, 1: 利回り, 2: ブレイク, 3: 築年, 4: 駅距離, 5: エリア, 6: 銀行評価, 7: 構造, 8: 稼働率, 9: 特記事項, 10: その他, 11: 応答なし',
    research_ng_reason JSON NULL COMMENT 'NG理由。JSON配列形式で選択値IDを保存。選択値IDとラベルの対応は property_option_values テーブルを参照。選択値: 0: 金額負け(他決), 1: 売主都合の売止, 2: 遵法性違反(瑕疵含む), 3: 銀行評価NG, 4: 売主金額合意NG',
    research_ng_reason_detail TEXT NULL COMMENT 'NG理由（詳細）',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_synced_at TIMESTAMP NULL,
    INDEX idx_hubspot_id (hubspot_id),
    INDEX idx_last_synced_at (last_synced_at),
    INDEX idx_hubspot_owner_id (hubspot_owner_id),
    INDEX idx_lead_acquirer (lead_acquirer),
    INDEX idx_deal_creator (deal_creator),
    INDEX idx_dealstage (dealstage),
    FOREIGN KEY (hubspot_owner_id) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (lead_acquirer) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (deal_creator) REFERENCES owners(id) ON DELETE SET NULL,
    FOREIGN KEY (dealstage) REFERENCES pipeline_stages(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='販売取引テーブル';